# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:android)

#platform :android do
#  desc "Runs all the tests"
#  lane :test do
#    gradle(task: "test")
#  end

#  desc "Submit a new Beta Build to Crashlytics Beta"
#  lane :beta do
#    gradle(task: "clean assembleRelease")
#    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
#  end

 # desc "Deploy a new version to the Google Play"
 # lane :deploy do
 #   gradle(task: "clean assembleRelease")
 #   upload_to_play_store
 # end
#end

platform :android do
  desc "Android build and release to beta"
  lane :increase do
    increment_version_code(gradle_file_path:'./app/build.gradle.kts')
  end

  lane :beta do    
#    gradle(task: 'bundle', build_type: 'Release', project_dir:'./')
    supply(track: 'internal',aab: './app/build/outputs/bundle/release/app-release.aab')
  end

  lane :release_to_appcenter do
    appcenter_upload(
      api_token: "bf1d52d0dad72826050f65b58a6574524d6fe7e5",
      owner_name: "luismendeze",
      app_name: "required-action-simulation",
      apk: "./app/build/outputs/apk/release/app-release.apk",      
      destinations: "beta-testers-required-actions-app",
      release_notes: "Release notes for this build",
      notify_testers: true # set to true if you want to notify testers
    )
  end
  



end